### ISSUE TITLE
Release on PGXN?

### ISSUE THREAD

**Issue by theory** [tvondra/count_distinct#10]
The latest release [on PGXN](https://pgxn.org/dist/count_distinct/) is 1.3.2. Time to release 3.0.0?

**Comment by tvondra** [comment]
Thanks for reminding me, I'll look into that. I wasn't paying much attention to this extension for a while, but I guess it deserves some update - also because of the PostgreSQL 12 release.

**Comment by tvondra** [comment]
I've released 3.0.1.
